# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stream_processing_pb2 as stream__processing__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stream_processing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskManagerServiceStub(object):
    """gRPC Services

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeployTask = channel.unary_unary(
                '/stream_processing.TaskManagerService/DeployTask',
                request_serializer=stream__processing__pb2.DeployTaskRequest.SerializeToString,
                response_deserializer=stream__processing__pb2.DeployTaskResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/stream_processing.TaskManagerService/CancelTask',
                request_serializer=stream__processing__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=stream__processing__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/stream_processing.TaskManagerService/GetMetrics',
                request_serializer=stream__processing__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=stream__processing__pb2.GetMetricsResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/stream_processing.TaskManagerService/Heartbeat',
                request_serializer=stream__processing__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=stream__processing__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class TaskManagerServiceServicer(object):
    """gRPC Services

    """

    def DeployTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeployTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployTask,
                    request_deserializer=stream__processing__pb2.DeployTaskRequest.FromString,
                    response_serializer=stream__processing__pb2.DeployTaskResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=stream__processing__pb2.CancelTaskRequest.FromString,
                    response_serializer=stream__processing__pb2.CancelTaskResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=stream__processing__pb2.GetMetricsRequest.FromString,
                    response_serializer=stream__processing__pb2.GetMetricsResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=stream__processing__pb2.HeartbeatRequest.FromString,
                    response_serializer=stream__processing__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream_processing.TaskManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stream_processing.TaskManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskManagerService(object):
    """gRPC Services

    """

    @staticmethod
    def DeployTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream_processing.TaskManagerService/DeployTask',
            stream__processing__pb2.DeployTaskRequest.SerializeToString,
            stream__processing__pb2.DeployTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream_processing.TaskManagerService/CancelTask',
            stream__processing__pb2.CancelTaskRequest.SerializeToString,
            stream__processing__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream_processing.TaskManagerService/GetMetrics',
            stream__processing__pb2.GetMetricsRequest.SerializeToString,
            stream__processing__pb2.GetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream_processing.TaskManagerService/Heartbeat',
            stream__processing__pb2.HeartbeatRequest.SerializeToString,
            stream__processing__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class JobManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/stream_processing.JobManagerService/SubmitJob',
                request_serializer=stream__processing__pb2.JobSubmission.SerializeToString,
                response_deserializer=stream__processing__pb2.JobSubmissionResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/stream_processing.JobManagerService/GetJobStatus',
                request_serializer=stream__processing__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=stream__processing__pb2.GetJobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/stream_processing.JobManagerService/CancelJob',
                request_serializer=stream__processing__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=stream__processing__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.TriggerCheckpoint = channel.unary_unary(
                '/stream_processing.JobManagerService/TriggerCheckpoint',
                request_serializer=stream__processing__pb2.TriggerCheckpointRequest.SerializeToString,
                response_deserializer=stream__processing__pb2.TriggerCheckpointResponse.FromString,
                _registered_method=True)
        self.AcknowledgeCheckpoint = channel.unary_unary(
                '/stream_processing.JobManagerService/AcknowledgeCheckpoint',
                request_serializer=stream__processing__pb2.AcknowledgeCheckpointRequest.SerializeToString,
                response_deserializer=stream__processing__pb2.AcknowledgeCheckpointResponse.FromString,
                _registered_method=True)


class JobManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=stream__processing__pb2.JobSubmission.FromString,
                    response_serializer=stream__processing__pb2.JobSubmissionResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=stream__processing__pb2.GetJobStatusRequest.FromString,
                    response_serializer=stream__processing__pb2.GetJobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=stream__processing__pb2.CancelJobRequest.FromString,
                    response_serializer=stream__processing__pb2.CancelJobResponse.SerializeToString,
            ),
            'TriggerCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerCheckpoint,
                    request_deserializer=stream__processing__pb2.TriggerCheckpointRequest.FromString,
                    response_serializer=stream__processing__pb2.TriggerCheckpointResponse.SerializeToString,
            ),
            'AcknowledgeCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeCheckpoint,
                    request_deserializer=stream__processing__pb2.AcknowledgeCheckpointRequest.FromString,
                    response_serializer=stream__processing__pb2.AcknowledgeCheckpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream_processing.JobManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stream_processing.JobManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream_processing.JobManagerService/SubmitJob',
            stream__processing__pb2.JobSubmission.SerializeToString,
            stream__processing__pb2.JobSubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream_processing.JobManagerService/GetJobStatus',
            stream__processing__pb2.GetJobStatusRequest.SerializeToString,
            stream__processing__pb2.GetJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream_processing.JobManagerService/CancelJob',
            stream__processing__pb2.CancelJobRequest.SerializeToString,
            stream__processing__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream_processing.JobManagerService/TriggerCheckpoint',
            stream__processing__pb2.TriggerCheckpointRequest.SerializeToString,
            stream__processing__pb2.TriggerCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream_processing.JobManagerService/AcknowledgeCheckpoint',
            stream__processing__pb2.AcknowledgeCheckpointRequest.SerializeToString,
            stream__processing__pb2.AcknowledgeCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
